---
- name: "Add repos from config"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck|default(true)|bool }}"
  when: "'baseurl' in item"
  loop: "{{ additional_repos }}"

- name: "Add repos from files"
  get_url:
    url: "{{ item.from_file }}"
    dest: "/etc/yum.repos.d/{{ item.from_file|regex_replace('[^a-zA-Z0-9]+', '_') }}.repo"
    timeout: 30
    force: yes
  when: "'from_file' in item"
  retries: 3
  delay: 10
  register: result
  until: not result.failed
  loop: "{{ additional_repos }}"

- name: "Get needed certificates from files"
  ansible.builtin.get_url:
    url: "{{ item.needs_cert }}"
    dest: "/etc/pki/ca-trust/source/anchors/"
    timeout: 30
  when: "'from_file' in item and 'needs_cert' in item"
  retries: 3
  delay: 10
  register: result
  until: not result.failed
  loop: "{{ additional_repos }}"

- name: "Import needed certificates from files"
  ansible.builtin.command: update-ca-trust
  when: "'from_file' in item and 'needs_cert' in item"
  loop: "{{ additional_repos }}"

- name: "Apply repos from files fixes"
  lineinfile:
    path: "/etc/yum.repos.d/{{ item.from_file|regex_replace('[^a-zA-Z0-9]+', '_') }}.repo"
    regexp: "{{ item.fix_regexp }}"
    line: "{{ item.fix_line }}"
  when: "'from_file' in item and 'fix_regexp' in item and 'fix_line' in item"
  loop: "{{ additional_repos }}"

- name: "Add repos from rpms"
  yum:
    name: "{{ item.from_rpm }}"
    state: present
    disable_gpg_check: "{{ item.disable_gpg_check|default(False) }}"
  when: "'from_rpm' in item"
  retries: 3
  delay: 10
  register: result
  until: not result.failed
  loop: "{{ additional_repos }}"
...
